# Generated by Django 3.0.4 on 2020-03-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user_id', models.CharField(max_length=100)),
                ('main_resp_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_special_dates', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('card_text', models.TextField(max_length=2000)),
                ('date_starts', models.DateField()),
                ('date_ends', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DateUserCardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_ids', models.CharField(default='[]', max_length=300)),
                ('date', models.DateField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='CardLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.CardCategory'),
        ),
        migrations.CreateModel(
            name='BotUserToCardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
                ('card_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.CardCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookEveningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed_date', models.DateField()),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.Card')),
            ],
        ),
    ]
