# Generated by Django 3.0.6 on 2020-05-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcurBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('telegram_bot_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user_id', models.CharField(max_length=100)),
                ('main_resp_path', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('last_active', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qteam_bot.AcurBot')),
            ],
        ),
        migrations.CreateModel(
            name='CardShowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list_json', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('short_descr', models.CharField(max_length=1000)),
                ('long_descr', models.CharField(max_length=2000)),
                ('brand', models.CharField(max_length=200)),
                ('keywords', models.TextField(max_length=2000)),
                ('floor', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('plan_image', models.ImageField(null=True, upload_to='')),
                ('store_image', models.ImageField(null=True, upload_to='')),
                ('plan_pic_file_json', models.CharField(default='{}', max_length=100000)),
                ('store_pic_file_json', models.CharField(default='{}', max_length=100000)),
                ('is_availible_for_subscription', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qteam_bot.AcurBot')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qteam_bot.StoreCategory')),
            ],
        ),
        migrations.CreateModel(
            name='StartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrgSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.Store')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qteam_bot.BotUser')),
            ],
        ),
    ]
